config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }

  resources :accounts do
    resources :orders
  end

  resources :orders do
    resources :order_items
  end

  resources :charges

  resources :books

  root to: "books#index"
end

app/models/account.rb
class Account < ApplicationRecord
  has_one :user
  has_many :orders
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :order_items
  validates :price, :title, :description, :length, :stock, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :account

  validates :status, :total_price, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :book
  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :account, foreign_key: :account_id, optional: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :cart_items
  helper_method :cart_cost
  helper_method :order_history

  def order_history
    current_user.account.orders.select{ |order| order.status != "In progress"}
  end

  def cart_items
    current_user.account.orders.last.order_items.sum { |item| item.quantity }
  end

  def cart_cost
    cost = 0
    current_user.account.orders.last.order_items.each do |item|
      cost += (item.book.price * item.quantity)
    end
    cost
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @amount = params[:amount].to_f
  end

  def create
    # byebug
    # Amount in cents
    amount = params[:amount].to_f
    @amount = amount/100

    # customer = Stripe::Customer.create(
    #   :email => params[:stripeEmail],
    #   :source  => params[:stripeToken]
    # )
    charge = Stripe::Charge.create(
      :amount      => amount.to_i,
      :source => params[:stripeToken],
      :currency    => 'usd',
      # :customer => customer.id,
    )

    current_user.account.orders.last.update(:status => 'Resolved')
    current_user.account.orders.create
    flash[:alert] = "Order successfully proccessed!"

    redirect_to books_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action only: [:show] do
    redirect_to books_path unless current_user.account_id == params[:account_id].to_i || current_user.admin
  end

  def new
    order = Order.find(params[:order_id])
    book_id = params[:format].to_i

    book = order.order_items.find {|item| item.book_id == book_id}
    unless book
      item = order.order_items.create(quantity: 1, book_id: book_id)
    else
      book.update_attribute :quantity, book.quantity + 1
    end
    #
    # new_order_item = OrderItem.new(quantity:1, order_id: order_id, book_id: book_id )
    #
    #
    # if !current_user.account.orders.last.order_items.any?
    #   new_order_item.save
    # end
    #
    # new_item = true
    #
    # current_user.account.orders.last.order_items.each do |item|
    #   if new_order_item.book_id.to_i == item.book.id.to_i
    #     value = item.quantity += 1
    #     item.update(quantity: value)
    #     new_item = false
    #   end
    #   byebug
    # end
    #
    # if new_item == true
    #   new_order_item.save
    # end
    #
    #
    redirect_to account_order_path(current_user.account, current_user.account.orders.last)

  end




end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action only: [:show] do
    redirect_to books_path unless current_user.account_id == params[:account_id].to_i || current_user.admin
  end

  def show
    @account = Account.find(params[:account_id])
    @order = Order.find(params[:id])
  end




end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

# Initializing the user with account and order.
    resource.account = Account.create(name: resource.name)
    resource.save
    resource.account.orders.create

    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  def destroy
  resource.account.orders.destroy_all
  id = resource.account_id
  resource.destroy
  Account.find(id).destroy
  Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
  set_flash_message! :notice, :destroyed
  yield resource if block_given?
  respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/books/index.html.erb
<h3>books</h3>
<% @books.each do |book| %>
  <div class="book media">
    <div class="media-left media-top">
      <%= link_to book_path(book) do %>
        <%= image_tag book.img_src, class: "media-object", size: "90x135" %>
      <% end %>
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to book.title, book_path(book)%>
      </h4>
      <p>By <%= book.author %></p>
      <p><%= book.description %></p>
      <p>In Stock: <%= book.stock %></p>

      <% if current_user %>
      <%= render partial: "layouts/add_to_cart", locals: { book: book }%>
      <% end %>

    </div>
  </div>
<% end %>

app/views/books/show.html.erb
<div class="book-description row">
  <div class="col-sm-6">
    <h3><%= @book.title%></h3>
    <p>by <%= @book.author%></p>
    <p>price: $<%= @book.price %></p>
    <p>summary: <%= @book.description %></p>
    <p>length: <%= @book.length %> pages</p>
    <% if current_user && current_user.admin %>
      <p>
        <%= link_to "edit book", edit_book_path(@book)%> -
        <%= link_to "delete book", book_path(@book), method: :delete%>
      </p>
    <% end %>
  </div>
  <div class="col-sm-6">
    <%= image_tag @book.img_src, size: "300x450"%>
  </div>

</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$<%= @amount%></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $<%= @amount/100 %></span>
    </label>
  </article>

    <%= hidden_field_tag :amount, "#{@amount}"%>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Your order of books"
            data-amount="<%= @amount.to_i %>"
            data-locale="auto">
    </script>
<% end %>

app/views/layouts/_add_to_cart.html.erb
<% if current_user.account %>
<%= link_to "Add to Cart", new_order_order_item_path(current_user.account.orders.last, book.id) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row navigation">
        <%= link_to books_path do %>
          <h1>book store</h1>
        <% end %>
        <ul class="header-nav">
          <% if current_user && current_user.admin %>
            <li>
              <%=link_to "add book", new_book_path %>
            </li>
            <li>
              <%= link_to "profile", edit_user_registration_path %>
            </li>
            <li>
              <%=link_to "sign out", destroy_user_session_path, method: :delete %>
            </li>
          <% elsif  current_user %>
            <li>
              <%= link_to "Cart (#{cart_items}) - $#{cart_cost}", account_order_path(current_user.account, current_user.account.orders.last)  %>

            </li>
            <li>
              <%= link_to "profile", edit_user_registration_path %>
            </li>
            <li>
              <%=link_to "sign out", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%=link_to "sign in", new_user_session_path %>
            </li>
            <li>
              <%=link_to "sign up", new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>



      <%= flash[:alert] %>
      <%= flash[:notice] %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/show.html.erb
<h1>Your Shopping Cart</h1>

<ul>
<% @order.order_items.each do |item| %>
  <li>
    <%= item.book.title %>
    $<%= item.book.price %>
    Qty:<%= item.quantity %>
    Price: $<%= (item.book.price)*(item.quantity)%>
  </li>
<% end %>
<ul>

<hr>

<p>Pay this amount: $<%= cart_cost%></p>

<%= link_to 'Pay Now', {:controller => "charges", :action => "new", :amount => cart_cost.*(100) } %>